---
name: CLA Assistant
on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: signatures/version1/cla.json
          path-to-document: https://github.com/wkentaro/labelme/blob/main/CLA.md
          branch: cla-signatures
          allowlist: wkentaro,bot*
