---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: qttools5-dev
          version: 1.0
      - run: make setup
      - run: make check
